# SPDX-License-Identifier: MIT
---
- name: Generate package manager specific facts
  ansible.builtin.set_fact:
    pm_facts:
      apk:
        dnsmasq_package: dnsmasq
        dnsmasq_service: dnsmasq
        bind_package: bind
        bind_service: bind
        unbound_package: unbound
        unbound_service: unbound
      apt:
        dnsmasq_package: dnsmasq
        dnsmasq_service: dnsmasq
        bind_package: bind9
        bind_service: named
        unbound_package: unbound
        unbound_service: unbound
      yum:
        dnsmasq_package: dnsmasq
        dnsmasq_service: dnsmasq
        bind_package: bind
        bind_service: bind
        unbound_package: unbound
        undound_service: unbound
- name: Generate package facts
  ansible.builtin.package_facts:
    manager:
      - apk
      - apt
      - rpm
- name: Generate service facts
  ansible.builtin.service_facts:
- name: Privelege escalation
  become: true
  become_method: community.general.doas
  block:
    - name: Generate resolv.conf file
      ansible.builtin.template:
        src: templates/resolv.conf.j2
        dest: /etc/resolv.conf
        mode: "0644"
      notify:
        - Restart DNS
      tags: dns

    - name: Prepare disks
      ansible.builtin.import_tasks: disks.yml
      tags: disks

    - name: Configure sysctl params
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        reload: true

    # TODO download its from web
    - name: Install K8S components
      ansible.builtin.package:
        name: "{{ common_components }}"
        state: present

    # TODO generate containerd/config.toml
    - name: Enable kubelet service
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: true
